### ISSUE TITLE
Error running with fresh project

### ISSUE THREAD

**Issue by 0xAlchemist** [bjartek/go-with-the-flow#1]
I'm getting an error when trying to start a new project with GWTF. It looks like we should try rolling back the flow-go-sdk version being imported in go.mod to version 0.10.0: 
https://github.com/bjartek/go-with-the-flow/blob/master/go.mod#L11

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x16ddde8]

goroutine 1 [running]:
github.com/onflow/flow-go-sdk/crypto.PrivateKey.PublicKey(...)
	/Users/br3wb0n1k/Programming/Go/pkg/mod/github.com/onflow/flow-go-sdk@v0.11.0/crypto/crypto.go:131
github.com/bjartek/go-with-the-flow/gwtf.(*GoWithTheFlowAccount).NewAccountKey(0xc000137ef8, 0xc0002b2b70)
	/Users/br3wb0n1k/Programming/Go/pkg/mod/github.com/bjartek/go-with-the-flow@v1.5.4/gwtf/setup.go:149 +0x48
github.com/bjartek/go-with-the-flow/gwtf.(*GoWithTheFlow).DeployContract(0xc000122fc0, 0x18a62b7, 0xc, 0x0, 0xffffffff, 0xc000040118)
	/Users/br3wb0n1k/Programming/Go/pkg/mod/github.com/bjartek/go-with-the-flow@v1.5.4/gwtf/account.go:35 +0x18a
main.main()
	/Users/br3wb0n1k/Programming/Flow/Projects/hockeyverse/demo/main.go:10 +0x3f
exit status 2
make: *** [demo] Error 1
```

Both machines that I've produced this error on are running: 
Flow emulator - v0.9.1
Go - v1.15.3

Here are the project files for reference: https://github.com/0xAlchemist/hockeyverse

Let's figure this out tomorrow if you're around :)

**Comment by bjartek** [comment]
Looks like I am using v10.0.0 of the flow cli. Can you try with that?

**Comment by 0xAlchemist** [comment]
That resolved the issue. Users need to specify the CLI version when installing, otherwise it defaults to v0.9.1:

`sh -ci  "$(curl -fsSL https://storage.googleapis.com/flow-cli/install.sh)" -- v0.10.0`
