### ISSUE TITLE
Proposal for a Usage section in Readme

### ISSUE THREAD

**Issue by louisguitton** [bjartek/go-with-the-flow#22]
Given most examples I saw in https://github.com/bjartek/go-with-the-flow/network/dependents?package_id=UGFja2FnZS0yMjc1NjE0OTAz use v1, I thought maybe it could be useful to add a `## Usage` section to the read me that shows how to get setup with v2.

I leave my proposed Usage section below.

## Usage

First create a project directory, initialise the go module and install go-with-the-flow :
  ```sh
  mkdir test-gwtf && cd test-gtwf
  flow init
  go mod init github.com/louisguitton/test-gwtf
  go get github.com/bjartek/go-with-the-flow/v2/gwtf
  ```
Then create a task file:
  ```sh
  touch tasks/main.go
  ```
In that task file, you can then import gwtf and use it to your convenience, for example:
  ```go
  package main

  import (
	  "github.com/bjartek/go-with-the-flow/v2/gwtf"
  )
  
  func main() {
	  flow := gwtf.NewGoWithTheFlowInMemoryEmulator()
  
	  flow.CreateAccounts("0x02")
  }
  ```

In this occasion, we want to create an account called `0x02` so we need to edit `flow.json` to add that account to the accounts array:
```json
		"0x02": {
			"address": "01cf0e2f2f715450",
			"key": "62fc6b3839ebc9265ee5eae45191d6efcd60fcf143a936fc3db49312eb0f2ab6"
		}
```

Then you can run in one tab
```sh
flow emulator -v
```
and in another tab
```sh
go run ./tasks/main.go
```

**Comment by louisguitton** [comment]
the main issue that I faced while getting setup was that I had `github.com/onflow/flow-go-sdk v0.24.0` previously installed and listed in my `go.mod`, and then I was getting the following error when running the minimal example:

```sh
→ go get github.com/bjartek/go-with-the-flow/v2/gwtf
# github.com/onflow/flow-cli/pkg/flowkit
../../../go/pkg/mod/github.com/onflow/flow-cli@v0.28.3/pkg/flowkit/keys.go:119:49: too many arguments in call to kmsClient.SignerForKey
	have (context.Context, flow.Address, cloudkms.Key)
	want (context.Context, cloudkms.Key)
../../../go/pkg/mod/github.com/onflow/flow-cli@v0.28.3/pkg/flowkit/transaction.go:108:14: assignment mismatch: 1 variable but cadence.NewString returns 2 values
../../../go/pkg/mod/github.com/onflow/flow-cli@v0.28.3/pkg/flowkit/transaction.go:109:14: assignment mismatch: 1 variable but cadence.NewString returns 2 values
# github.com/onflow/flow-go/fvm
../../../go/pkg/mod/github.com/onflow/flow-go@v0.18.4/fvm/env.go:32:5: cannot use &hostEnv{} (type *hostEnv) as type runtime.Interface in assignment:
	*hostEnv does not implement runtime.Interface (missing AllocateStorageIndex method)
../../../go/pkg/mod/github.com/onflow/flow-go@v0.18.4/fvm/env.go:138:19: cannot use e (type *hostEnv) as type runtime.Interface in field value:
	*hostEnv does not implement runtime.Interface (missing AllocateStorageIndex method)
../../../go/pkg/mod/github.com/onflow/flow-go@v0.18.4/fvm/script.go:84:4: cannot use env (type *hostEnv) as type runtime.Interface in field value:
	*hostEnv does not implement runtime.Interface (missing AllocateStorageIndex method)
../../../go/pkg/mod/github.com/onflow/flow-go@v0.18.4/fvm/transactionContractFunctionInvocator.go:62:4: cannot use env (type *hostEnv) as type runtime.Interface in field value:
	*hostEnv does not implement runtime.Interface (missing AllocateStorageIndex method)
../../../go/pkg/mod/github.com/onflow/flow-go@v0.18.4/fvm/transactionInvocator.go:135:5: cannot use env (type *hostEnv) as type runtime.Interface in field value:
	*hostEnv does not implement runtime.Interface (missing AllocateStorageIndex method)
../../../go/pkg/mod/github.com/onflow/flow-go@v0.18.4/fvm/transactionInvocator.go:277:43: not enough arguments in call to interpreter.NewHostFunctionValue
	have (func(interpreter.Invocation) interpreter.Value)
	want (interpreter.HostFunction, *sema.FunctionType)
```

Tracing that down to the fact I should have `github.com/onflow/flow-go-sdk v0.20.1-0.20210623043139-533a95abf071` took me some time, and a Usage section would have helped me I think.

**Comment by bjartek** [comment]
Thanks for adding this. Do you want to send a PR to get credit?

**Comment by bjartek** [comment]
Part of your comment above is not completely accurate. 

When you are using 

`flow := gwtf.NewGoWithTheFlowInMemoryEmulator()` 

you do not need to run an emulator in a seperate tab. 

Also the recomended way of adding new accounts is adding them to the relevant deployment network without any contracts in them.

**Comment by louisguitton** [comment]
ah yeah well spotted, actually my code uses `gwtf.NewGoWithTheFlowEmulator().CreateAccounts("0x02").InitializeContracts()` so far and I messed up the PR description.

I'll open a draft PR. bare with me as I'm figuring out also how I use your great tool etc... so worse case you cherry pick 1 or 2 commits and close the rest, and leave with some user feedback 🙏
